FINALS = ['Key.up',
          'Key.down',
          'Key.left',
          'Key.right',
          'Key.space',
          'Key.enter',
          'Key.shift',
          'Key.shift_r',
          'Key.delete',
          'Key.backspace']

special_converter = {'å': 'a',
                     '∫': 'b',
                     'ç': 'c',
                     '∂': 'd',
                     '<14>': 'e',
                     'ƒ': 'f',
                     '©': 'g',
                     '˙': 'h',
                     '<34>': 'i',
                     '∆': 'j',
                     '˚': 'k',
                     '¬': 'l',
                     'µ': 'm',
                     '<45>': 'n',
                     'ø': 'o',
                     'π': 'p',
                     'œ': 'q',
                     '®': 'r',
                     'ß': 's',
                     '†': 't',
                     '<32>': 'u',
                     '√': 'v',
                     '∑': 'w',
                     '≈': 'x',
                     '¥': 'y',
                     'Ω': 'z',
                     }

MODIFIERS = {'Key.ctrl': 1,
             'Key.shift': 2,
             'Key.alt': 3,
             'Key.cmd': 4,
             'Key.ctrl_r': 5,
             'Key.shift_r': 6,
             'Key.alt_r': 7,
             'Key.cmd_r': 8,
             'Key.backspace': 9,
             'Key.delete': 10,
             'Key.tab': 11,
             'Key.home': 12,
             'Key.end': 13,
             'Key.page_up': 14,
             'Key.page_down': 15,
             'Key.space': 16,
             'Key.enter': 17,
             'Key.up': 18,
             'Key.down': 19,
             'Key.left': 20,
             'Key.right': 21}

TEMPLATE = {'MIDI': ['in', 'out']
            }
